name: Weekly Team Sync
on:
  watch
  # schedule:
  #   - cron: 20 07 * * 1
  
jobs:
  create_issue:
    name: Create team sync issue
    runs-on: ubuntu-latest
    steps:
      - name: Create team sync issue
        uses: imjohnbo/issue-bot@v3
        with:
          assignees: "praveendasan"
          labels: "bug"
          title: "Weekly Team sync"
          body:
            ### Agenda
            
             - [ ] Start the recording
             - [ ] Check-ins
             - [ ] Discussion points
             - [ ] Post the recording
             
             ### Discussion Points
             Add things to discuss below
             
          pinned: false
          close-previous: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
